name: easy_english
description: "Direct End-to-End Encrypted P2P English Speaking Practice App with RevenueCat Monetization & Gemini AI Speaking Coach."
publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: ^3.13.4

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_webrtc: ^1.2.1
  purchases_flutter: ^8.0.0
  purchases_ui_flutter: ^8.0.0
  cryptography: ^2.7.0
  http: ^1.2.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
